sudo: required
dist: trusty
language:
  - node_js
  - cpp
compiler:
  - gcc
node_js:
  - "5"
  - "5.1"
  - "5.6"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
services:
  - mongodb
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9